// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "../ThreadId";
import type { ThreadPlanRun } from "./ThreadPlanRun";

export type ThreadPlanRunUpdatedEvent = { threadId: ThreadId, turnId?: string, planRun: ThreadPlanRun, };
