// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "../ThreadId";
import type { ThreadPlanRunStatus } from "./ThreadPlanRunStatus";

export type ThreadPlanRun = { threadId: ThreadId, planRunId?: string, planText: string, status: ThreadPlanRunStatus, tokenBudget?: bigint, tokensUsed: bigint, timeUsedSeconds: bigint, createdAt: bigint, updatedAt: bigint, };
