// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSlimmingScope } from "./InputSlimmingScope";
import type { InputSlimmingTokenStats } from "./InputSlimmingTokenStats";

export type InputSlimmingStats = { scope: InputSlimmingScope, last: InputSlimmingTokenStats, total: InputSlimmingTokenStats, };
