// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewDelivery } from "./ReviewDelivery";
import type { ReviewTarget } from "./ReviewTarget";

export type ReviewStartParams = { threadId: string, target: ReviewTarget,
/**
 * Where to run the review. Inline is the only supported mode; omitted means inline.
 */
delivery: ReviewDelivery | null, };
