// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";

export type ReviewStartResponse = { turn: Turn,
/**
 * Identifies the thread where the review runs.
 *
 * This is the original thread id for supported inline reviews.
 */
reviewThreadId: string, };
