// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowStatus } from "./WorkflowStatus";
import type { WorkflowValidationError } from "./WorkflowValidationError";

export type WorkflowUpdateEvent = { workflow_id: string, status: WorkflowStatus, current_step: string | null, completed_steps: Array<string>, last_error: WorkflowValidationError | null, };
