// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedCommand } from "./ParsedCommand";
import type { ThreadId } from "./ThreadId";

export type ExecCommandApprovalParams = { conversationId: ThreadId,
/**
 * Use to correlate this with exec command begin/end runtime events.
 */
callId: string, command: Array<string>, cwd: string, reason: string | null, parsedCmd: Array<ParsedCommand>, };
