// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityKind } from "./IdentityKind";
import type { Settings } from "./Settings";

/**
 * Identity for an LHA session.
 */
export type Identity = { kind: IdentityKind, settings: Settings, };
