// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityCapabilities } from "./IdentityCapabilities";
import type { IdentityKind } from "./IdentityKind";
import type { ReasoningEffort } from "./ReasoningEffort";

/**
 * A mask for identity settings, allowing partial updates.
 * All fields except `name` are optional, enabling selective updates.
 */
export type IdentityMask = { name: string, kind: IdentityKind | null, model: string | null, reasoning_effort: ReasoningEffort | null | null, developer_instructions: string | null | null, capabilities: IdentityCapabilities, };
