// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSlimmingTokenStats } from "./InputSlimmingTokenStats";
import type { InputSlimmingScope } from "./protocol/InputSlimmingScope";

export type InputSlimmingEvent = { scope: InputSlimmingScope, last: InputSlimmingTokenStats, total: InputSlimmingTokenStats, };
