// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputSlimmingTokenStats = { tokens_before: bigint, tokens_after: bigint, tokens_saved: bigint, replacements: bigint, };
