// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolResultContentItem } from "./ToolResultContentItem";

export type ToolResultPayload = { "type": "structured", content: string, content_items?: Array<ToolResultContentItem>, success?: boolean, } | { "type": "text", output: string, };
