// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentItem } from "./ContentItem";
import type { ReasoningItemContent } from "./ReasoningItemContent";
import type { ReasoningItemReasoningSummary } from "./ReasoningItemReasoningSummary";
import type { ToolCallPayload } from "./ToolCallPayload";
import type { ToolResultPayload } from "./ToolResultPayload";
import type { JsonValue } from "./serde_json/JsonValue";

export type TranscriptItem = { "type": "message", id?: string, role: string, content: Array<ContentItem>, end_turn?: boolean, } | { "type": "reasoning", id: string, summary: Array<ReasoningItemReasoningSummary>, content?: Array<ReasoningItemContent>, encrypted_content: string | null, } | { "type": "hosted_activity", id?: string, activity_type: string, status?: string, payload: JsonValue, } | { "type": "tool_call", id?: string, call_id: string, tool_name: string, payload: ToolCallPayload, } | { "type": "tool_result", call_id: string, tool_name: string, payload: ToolResultPayload, } | { "type": "unknown", raw: JsonValue, };
