// Former standalone product crates now live as private modules in `lha`.
// Their crate-level public facades are intentionally preserved for internal
// compatibility, even when not every re-export is used by the single binary.
#![allow(dead_code, unused_imports)]

#[path = "../product/agent_runtime/src/lib.rs"]
pub(crate) mod agent;
#[path = "../product/ansi_escape/src/lib.rs"]
pub(crate) mod ansi_escape;
#[path = "../product/app_server/src/lib.rs"]
pub(crate) mod app_server;
#[path = "../product/app_server_protocol/src/lib.rs"]
pub(crate) mod app_server_protocol;
#[path = "../product/apply_patch/src/lib.rs"]
pub(crate) mod apply_patch;
#[path = "../product/arg0/src/lib.rs"]
pub(crate) mod arg0;
#[path = "../product/async_utils/src/lib.rs"]
pub(crate) mod async_utils;
#[path = "../product/common/src/lib.rs"]
pub(crate) mod common;
#[path = "../product/exec_cli/src/lib.rs"]
pub(crate) mod exec_cli;
#[path = "../product/execpolicy/src/lib.rs"]
pub(crate) mod execpolicy;
#[path = "../product/feedback/src/lib.rs"]
pub(crate) mod feedback;
#[path = "../product/file_search/src/lib.rs"]
pub(crate) mod file_search;
#[path = "../product/git_utils/src/lib.rs"]
pub(crate) mod git_utils;
#[path = "../product/identity/src/lib.rs"]
pub(crate) mod identity;
#[path = "../product/keyring_store/src/lib.rs"]
pub(crate) mod keyring_store;
#[path = "../product/linux_sandbox/src/lib.rs"]
pub(crate) mod linux_sandbox;
#[path = "../product/mcp_server/src/lib.rs"]
pub(crate) mod mcp_server;
#[path = "../product/mcp_types/src/lib.rs"]
pub(crate) mod mcp_types;
#[path = "../product/memories_read/src/lib.rs"]
pub(crate) mod memories_read;
#[path = "../product/memories_write/src/lib.rs"]
pub(crate) mod memories_write;
#[path = "../product/otel/src/lib.rs"]
pub(crate) mod otel;
#[path = "../product/process_hardening/src/lib.rs"]
pub(crate) mod process_hardening;
#[path = "../product/protocol/src/lib.rs"]
pub(crate) mod protocol;
#[path = "../product/responses_api_proxy/src/lib.rs"]
pub(crate) mod responses_api_proxy;
#[path = "../product/rmcp_client/src/lib.rs"]
pub(crate) mod rmcp_client;
#[path = "../product/secrets/src/lib.rs"]
pub(crate) mod secrets;
#[path = "../product/state/src/lib.rs"]
pub(crate) mod state;
#[path = "../product/stdio_to_uds/src/lib.rs"]
pub(crate) mod stdio_to_uds;
#[path = "../product/tui_app/src/lib.rs"]
pub(crate) mod tui_app;
#[path = "../product/utils_absolute_path/src/lib.rs"]
pub(crate) mod utils_absolute_path;
#[path = "../product/utils_cache/src/lib.rs"]
pub(crate) mod utils_cache;
#[path = "../product/utils_home_dir/src/lib.rs"]
pub(crate) mod utils_home_dir;
#[path = "../product/utils_image/src/lib.rs"]
pub(crate) mod utils_image;
#[path = "../product/utils_json_to_toml/src/lib.rs"]
pub(crate) mod utils_json_to_toml;
#[path = "../product/utils_pty/src/lib.rs"]
pub(crate) mod utils_pty;
#[path = "../product/utils_readiness/src/lib.rs"]
pub(crate) mod utils_readiness;
#[path = "../product/utils_sleep_inhibitor/src/lib.rs"]
pub(crate) mod utils_sleep_inhibitor;
#[path = "../product/utils_string/src/lib.rs"]
pub(crate) mod utils_string;
#[path = "../product/windows_sandbox/src/lib.rs"]
pub(crate) mod windows_sandbox;
