// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentRef } from "./CollabAgentRef";
import type { ThreadId } from "./ThreadId";

export type CollabWaitingBeginEvent = {
/**
 * Thread ID of the sender.
 */
sender_thread_id: ThreadId,
/**
 * Thread ID of the receivers.
 */
receiver_thread_ids: Array<ThreadId>,
/**
 * Additional receiver metadata for UI consumers that want nicknames/roles.
 */
receiver_agents: Array<CollabAgentRef>,
/**
 * ID of the waiting call.
 */
call_id: string, };
