// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capabilities associated with an identity.
 */
export type IdentityCapabilities = { 
/**
 * Whether this identity is intended to have write-capable tools.
 * This is currently metadata only; tool exposure is not filtered from this field yet.
 */
write_tools: boolean, };
