// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskForApproval } from "./AskForApproval";
import type { ReasoningSummary } from "./ReasoningSummary";
import type { Verbosity } from "./Verbosity";

export type Profile = { approvalPolicy: AskForApproval | null, modelReasoningSummary: ReasoningSummary | null, modelVerbosity: Verbosity | null, };
