// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewConversationParams } from "./NewConversationParams";
import type { ThreadId } from "./ThreadId";
import type { TranscriptItem } from "./TranscriptItem";

export type ResumeConversationParams = { path: string | null, conversationId: ThreadId | null, history: Array<TranscriptItem> | null, overrides: NewConversationParams | null, };
