// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationItem } from "./ConversationItem";
import type { NewConversationParams } from "./NewConversationParams";
import type { ThreadId } from "./ThreadId";

export type ResumeConversationParams = { path: string | null, conversationId: ThreadId | null, history: Array<ConversationItem> | null, overrides: NewConversationParams | null, };
